Changes needed to support new jsx runtime
grafana/eslint-config-grafana pull request #38
Opened 2024-06-17 10:15 UTC by ashharrison90

- changes needed to support new JSX runtime
- bump major version

prereq for https://github.com/grafana/grafana/pull/88802/

won't merge and release until we're all ready in core as well 👍

2024-06-19 08:20 UTC, jackw commented
>won't merge and release until we're all ready in core as well 👍

This package is also used by plugins. If a plugin dev updates this will they need to update their tsconfig config and webpack config too?

2024-06-19 08:58 UTC, ashharrison90 commented
> > won't merge and release until we're all ready in core as well 👍
> 
> This package is also used by plugins. If a plugin dev updates this will they need to update their tsconfig config and webpack config too?

> > won't merge and release until we're all ready in core as well 👍
> 
> This package is also used by plugins. If a plugin dev updates this will they need to update their eslint config and webpack config too?

yes. do plugins typically manage their own dependencies, or do they rely on `create-plugin` to update them? or some mixture of both? 🤔 

either way, we should probably add a CHANGELOG to this repo to explain the changes. it will be something like:
- update `tsconfig-grafana` as well
- update the build to use new jsx runtime (this step will vary depending on the existing build, e.g. babel, esbuild, etc.)
- run the [react codemod](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports) on the plugin code

2025-09-24 12:16 UTC, jackw requested changes
Blocking this as the changes here will force plugins to use auto jsx which right now will bundle jsx-runtime into the plugin. This will cause the plugin to break when loaded in a version of Grafana running React 19. See [this comment](https://github.com/grafana/grafana-community-team/issues/553#issuecomment-3312256760) in the community team React 19 epic for further info.

We will get there but I don't want this creeping in and causing us more bother with the upgrade path for plugins.

2026-06-11 08:47 UTC, tolzhabayev commented
@jackw @ashharrison90 I would close this as stale and reopen if it becomes relevant

2026-06-11 09:17 UTC, ashharrison90 commented
i forgot this existed tbh. closing for now 👍

2026-06-11 09:17 UTC, closed without merging